In [ ]:
#Aim:to perform operation on Basic of Data Frame

In [2]:
#Name:Anushka Prashant Kawane
#Roll No.:25
#Sec:C
#Subject:ET2

Creating Series

In [2]:
import pandas as pd

In [4]:
Name = ["Asish", "Sagar", "Shrikant", "Lovely", "Saurabh"]
Name

['Asish', 'Sagar', 'Shrikant', 'Lovely', 'Saurabh']

In [5]:
Roll_list=pd.Series(Name,index=[1,2,3,4,5])
print(Roll_list)

1       Asish
2       Sagar
3    Shrikant
4      Lovely
5     Saurabh
dtype: object

Creating Data Frame

In [6]:
import pandas as pd

In [7]:
df=pd.DataFrame([[10,12,14,16],[11,18,15,21],[12,13,14,15]],
columns= ["CD","DBMS","DSS","CAO"])

In [8]:
df

   CD  DBMS  DSS  CAO
0  10    12   14   16
1  11    18   15   21
2  12    13   14   15

In [9]:
df.shape

(3, 4)

In [10]:
df.size

12

In [11]:
df.ndim

2

Adding Record (Row) to the data frame

In [12]:
df2=pd.DataFrame([[5,6,7,8]],
columns= ["CD","DBMS","DSS","CAO"])

In [13]:
df3=df.append(df2,ignore_index=True)

In [14]:
df3

   CD  DBMS  DSS  CAO
0  10    12   14   16
1  11    18   15   21
2  12    13   14   15
3   5     6    7    8

Adding Attribute (Columns) name DM

In [15]:
df3["DM"]=[12,15,16,14]

In [16]:
df3

   CD  DBMS  DSS  CAO  DM
0  10    12   14   16  12
1  11    18   15   21  15
2  12    13   14   15  16
3   5     6    7    8  14

Deleting Record from  df3 dataframe

In [17]:
df4=df3.drop(index=[1])

In [18]:
df4

   CD  DBMS  DSS  CAO  DM
0  10    12   14   16  12
2  12    13   14   15  16
3   5     6    7    8  14

Deleting Attribute (Columns) from df3 dataframe

In [19]:
df5=df3.drop(columns=["DM"])

In [20]:
df5

   CD  DBMS  DSS  CAO
0  10    12   14   16
1  11    18   15   21
2  12    13   14   15
3   5     6    7    8

In [21]:
print("Mean of DSS:", df5["DSS"].mean())

Mean of DSS: 12.5

In [22]:
print("Median of DSS:", df5["DSS"].median())

Median of DSS: 14.0

In [23]:
print("Mode of DSS:", df5["DSS"].mode())

Mode of DSS: 0    14
dtype: int64

In [24]:
print("Max of DSS:", df5["DSS"].max())

Max of DSS: 15

In [25]:
print("Max of DSS:", df5["DSS"].min())

Max of DSS: 7